mycar/views/contact_views.py
from flask import Blueprint, render_template, url_for, request, g, flash
from werkzeug.utils import redirect
from mycar import db
from mycar.models import Dpfcar, Contact
from datetime import datetime
from mycar.views.auth_views import login_required
from sqlalchemy import and_, or_
bp = Blueprint('contact', __name__, url_prefix='/contact')


@bp.route('/regit/<int:dpfcar_id>/')
@login_required
def regit(dpfcar_id):
    dpfcar_one = Dpfcar.query.get_or_404(dpfcar_id)
    return render_template('contact/regit.html', dpfcar_one=dpfcar_one)


@bp.route('/create', methods=('POST',))
@login_required
def create():
    dpfcar_id = request.form['carid']
    ownername = request.form['ownername']
    ownertel = request.form['ownertel']
    owneretc = request.form['owneretc']
    ownernum4 = request.form['ownernum4']

    dpfcar_one = Dpfcar.query.get_or_404(dpfcar_id)
    contact_one = Contact(dpfcar=dpfcar_one, user=g.user, ownername=ownername, ownertel=ownertel,
                          owneretc=owneretc, ownernum4 = ownernum4, create_date=datetime.now(), update_date=datetime.now())

    dpfcar_one.contact_set.append(contact_one)
    g.user.contact_set.append(contact_one)
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/update', methods=('GET','POST'))
@login_required
def update():
    contact = Contact.query.filter_by(id=request.form['contactid']).first()
    contact.ownername = request.form['ownername']
    contact.ownertel = request.form['ownertel']
    contact.owneretc = request.form['owneretc']
    contact.ownernum4 = request.form['ownernum4']
    contact.update_date = datetime.now()
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/modify/<int:contact_id>', methods=('GET',))
@login_required
def modify(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    return render_template('contact/update.html', contact_one=contact)


@bp.route('/delete/<int:contact_id>', methods=('GET',))
@login_required
def delete(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    if g.user != contact.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('contact.result'))
    db.session.delete(contact)
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/result', methods=('GET', 'POST'))
@login_required
def result():
    contact_list = g.user.contact_set
    return render_template('contact/result.html', contact_list=contact_list)


@bp.route('/resultby', methods=('POST',))
@login_required
def resultby():

    if request.form['ownernum4'] :
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownernum4 == request.form['ownernum4'])).all()
    elif request.form['ownername'] :
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownername == request.form['ownername'])).all()
    elif request.form['ownertel']:
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownertel ==request.form['ownertel'])).all()
    else:
        contact_list = ""
    return render_template('contact/result.html', contact_list=contact_list, ownernum4=request.form['ownernum4'],ownername =request.form['ownername'],
                           ownertel=request.form['ownertel'])

mycar/views/dpfcar_views.py
from flask import Blueprint, render_template, url_for, request, flash
from werkzeug.utils import redirect
from werkzeug.utils import secure_filename
import mycar.searchnum
from mycar.models import Dpfcar
from sqlalchemy import or_, and_
from mycar.views.auth_views import login_required
import pandas as pd


bp = Blueprint('dpfcar', __name__, url_prefix='/dpfcar')

@bp.route('/result', methods=('POST',))
@login_required
def result():
    if request.form['carnumber']:
        carnumber = request.form['carnumber']
        carnumin = carnumber[-4:]
        car_num4_01 = carnumber[:-4]+carnumin[0:2] + "**"
        car_num4_02 = carnumber[:-4]+carnumin[0] + "**" + carnumin[3]
        car_num4_03 = carnumber[:-4]+"**" + carnumin[2:4]
        carkind = request.form['carkind']
        if request.form['carkind']:
            dpfcar_list = Dpfcar.query.filter(and_(
                or_(Dpfcar.carnumber == car_num4_01,
                    Dpfcar.carnumber == car_num4_02,
                    Dpfcar.carnumber == car_num4_03),
                Dpfcar.carkind == carkind)).all()
        else:
            dpfcar_list = Dpfcar.query.filter(
                or_(Dpfcar.carnumber == car_num4_01,
                    Dpfcar.carnumber == car_num4_02,
                    Dpfcar.carnumber == car_num4_03)).all()
    else:
        dpfcar_list = ""
    return render_template('search/result.html', dpfcar_list=dpfcar_list,carnumber=carnumber ,carkind=carkind)

@bp.route('/img_result', methods=('GET','POST'))
@login_required
def img_result():
    if request.method == 'POST':
        carnumimg= request.files['file'].read()

        # print(secure_filename(f.filename))
        try:
            carnumber = mycar.searchnum.search_num(carnumimg)
        except:
            flash('차량번호 이미지 찾기가 실패하였습니다.')
            # carnumber = ""
            # dpfcar_list = ""
            # return render_template('search/result.html', dpfcar_list=dpfcar_list, carnumber=carnumber)
            return redirect(url_for('dpfcar.go_imgbase'))
        carnumin = carnumber[-4:]
        car_num4_01 = carnumber[:-4]+carnumin[0:2] + "**"
        car_num4_02 = carnumber[:-4]+carnumin[0] + "**" + carnumin[3]
        car_num4_03 = carnumber[:-4]+"**" + carnumin[2:4]

        dpfcar_list = Dpfcar.query.filter(
            or_(Dpfcar.carnumber == car_num4_01,
                Dpfcar.carnumber == car_num4_02,
                Dpfcar.carnumber == car_num4_03)).all()
    else:
        dpfcar_list = ""
    return render_template('search/result.html', dpfcar_list=dpfcar_list,carnumber=carnumber )

@bp.route('/go_base', methods=('GET','POST'))
@login_required
def go_base():
    return render_template('search/base.html')

@bp.route('/go_imgbase', methods=('GET','POST'))
@login_required
def go_imgbase():
    return render_template('search/imgbase.html')

mycar/templates/search/base.html
{% extends 'basic.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="tm-call-to-action-box">

        <div class="tm-call-to-action-text">
             <li>
                <a class="nav-link" href="{{ url_for('dpfcar.go_imgbase') }}">이미지 검색으로</a>&nbsp;
            </li>
        <h3 class="tm-call-to-action-title">
            저감장치 대상 차량 번호검색
        </h3>
        <p class="tm-call-to-action-description">
            검색할 차의 <strong>차량번호</strong>을 입력하세요. 차량번호는 필수입니다.
        </p>


        <form action="{{ url_for('dpfcar.result') }}" class="tm-call-to-action-form" method="post">
<!--            <input type="text" name="car_place" id="car_place" placeholder="앞2자리+" class="tm-jiyuk-input" minlength="3" maxlength="10" required="">-->
            <div><label for="carnumber">  차량번호:</label>
            <input type="text" name="carnumber" id="carnumber" placeholder="검색할 번호입력" class="tm-car-input" minlength="6" required = "">
            </div>
            <label for="carkinds">  차량종류:</label>
            <input list="carkinds" name="carkind" id="carkind" placeholder="전체" class="tm-chajong-input">
            <datalist id="carkinds">
                <option value="전체">
                </option><option value="승용">
                </option><option value="승합">
                </option><option value="화물">
                </option><option value="특수">
            </option></datalist>

            <button type="submit" class="btn btn-primary">
            <strong>번호검색</strong>
        </form>
        </div>

    </div>
{% endblock %}

mycar/templates/search/imgbase.html
{% extends 'basic.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="tm-call-to-action-box">

        <div class="tm-call-to-action-text">
            <li>
                <a class="nav-link" href="{{ url_for('dpfcar.go_base') }}">번호 검색으로</a>&nbsp;
            </li>
        <h3 class="tm-call-to-action-title">
            저감장치 대상 차량 사진검색
        </h3>
        <p class="tm-call-to-action-description">
            검색할 차의 <strong>차량번호 사진파일</strong>을 먼저 선택 입력하세요.
        </p>


        <form action="{{ url_for('dpfcar.img_result') }}" class="tm-call-to-action-form" method="post" enctype="multipart/form-data" >
            <div><label for="carimg">  차량번호 사진:</label>
            <div><input type="file" name="file" id="carimg" required = "">
                <button type="submit" class="btn btn-primary">
                <strong>이미지검색</strong>
            </div>
            <img id="image_section" src="#" alt=" Upload Image" width="450"></img>
            </div>


            </button>
        </form></div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type='text/javascript'>
function readUploadImage( inputObject ){
     if (inputObject.files && inputObject.files[0]) {
        if ( !(/image/i).test(inputObject.files[0].type ) ){
				alert("이미지 파일을 선택해 주세요!");
				return false;
			}

        var reader = new FileReader();

        reader.onload = function (e) {
            $('#image_section').attr('src', e.target.result);
        }

        reader.readAsDataURL(inputObject.files[0]);
     }
}

$("#carimg").change(function(){
   readUploadImage(this);
});
</script>
{% endblock %}

mycar/templates/search/result.html
{% extends 'basic.html' %}
{% block content %}

        <div class="tm-call-to-action-box">

            <div class="tm-call-to-action-text">
                <li>
                <a class="nav-link" href="{{ url_for('dpfcar.go_base') }}">번호 검색으로</a>&nbsp;&nbsp;
                <a class="nav-link" href="{{ url_for('dpfcar.go_imgbase') }}">이미지 검색으로</a>&nbsp;
                </li>
            <h3 class="tm-call-to-action-title">
                저감장치 대상 차량 검색 결과
            </h3>
            <form action="{{ url_for('dpfcar.result') }}" class="tm-call-to-action-form" method="post">
    <!--            <input type="text" name="car_place" id="car_place" placeholder="앞2자리+" class="tm-jiyuk-input" minlength="3" maxlength="10" required="">-->
                <div><label for="carnumber">  차량번호:</label>
                <input type="text" name="carnumber" id="carnumber" value="{{ carnumber }}" class="tm-car-input" minlength="6" required = "">
                </div>
                <label for="carkinds">  차량종류:</label>
                <input list="carkinds" name="carkind" id="carkind" placeholder="{{ carkind }}" class="tm-chajong-input">
                <datalist id="carkinds">
                    <option value="전체">
                    </option><option value="승용">
                    </option><option value="승합">
                    </option><option value="화물">
                    </option><option value="특수">
                </option></datalist>

                <button type="submit" class="btn btn-primary">
                <strong>검색</strong>
                </button>
            </form>
            </div>
        </div>
        <div>

            <table style="width:100%">
                <thead>
                <tr class="table-head-tr">
                    <td>차량 번호</td>
                    <td>차량 연식</td>
                    <td>차량 차종</td>
                    <td>구 분</td>

                </tr>
                </thead>
                <tbody>
                {% if dpfcar_list %}
                    {% for dpfcar in dpfcar_list %}
                        <tr>
                            <td>{{ dpfcar.carnumber }}</td>
                            <td>{{ dpfcar.caryear }}</td>
                            <td>{{ dpfcar.carkind }}</td>
                            {% if dpfcar.contact_set %}
                                <td><a href="{{ url_for('contact.result') }}" >고객관리</a></td>
                            {% else %}
                                <td><a href="{{ url_for('contact.regit', dpfcar_id=dpfcar.id) }}" >등록하기</a></td>
                            {% endif %}


                        </tr>
                    {% endfor %}

                {% else %}
                    <tr>
                        <td colspan = "4" >** 검색 결과가 없습니다.**</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

{% endblock %}