mycar/views/contact_views.py
from flask import Blueprint, render_template, url_for, request, g, flash
from werkzeug.utils import redirect
from mycar import db
from mycar.models import Dpfcar, Contact
from datetime import datetime
from mycar.views.auth_views import login_required
from sqlalchemy import and_, or_
bp = Blueprint('contact', __name__, url_prefix='/contact')


@bp.route('/regit/<int:dpfcar_id>/')
@login_required
def regit(dpfcar_id):
    dpfcar_one = Dpfcar.query.get_or_404(dpfcar_id)
    return render_template('contact/regit.html', dpfcar_one=dpfcar_one)


@bp.route('/create', methods=('POST',))
@login_required
def create():
    dpfcar_id = request.form['carid']
    ownername = request.form['ownername']
    ownertel = request.form['ownertel']
    owneretc = request.form['owneretc']
    ownernum4 = request.form['ownernum4']

    dpfcar_one = Dpfcar.query.get_or_404(dpfcar_id)
    contact_one = Contact(dpfcar=dpfcar_one, user=g.user, ownername=ownername, ownertel=ownertel,
                          owneretc=owneretc, ownernum4 = ownernum4, create_date=datetime.now(), update_date=datetime.now())

    dpfcar_one.contact_set.append(contact_one)
    g.user.contact_set.append(contact_one)
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/update', methods=('GET','POST'))
@login_required
def update():
    contact = Contact.query.filter_by(id=request.form['contactid']).first()
    contact.ownername = request.form['ownername']
    contact.ownertel = request.form['ownertel']
    contact.owneretc = request.form['owneretc']
    contact.ownernum4 = request.form['ownernum4']
    contact.update_date = datetime.now()
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/modify/<int:contact_id>', methods=('GET',))
@login_required
def modify(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    return render_template('contact/update.html', contact_one=contact)


@bp.route('/delete/<int:contact_id>', methods=('GET',))
@login_required
def delete(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    if g.user != contact.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('contact.result'))
    db.session.delete(contact)
    db.session.commit()
    return redirect(url_for('contact.result'))


@bp.route('/result', methods=('GET', 'POST'))
@login_required
def result():
    contact_list = g.user.contact_set
    return render_template('contact/result.html', contact_list=contact_list)


@bp.route('/resultby', methods=('POST',))
@login_required
def resultby():

    if request.form['ownernum4'] :
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownernum4 == request.form['ownernum4'])).all()
    elif request.form['ownername'] :
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownername == request.form['ownername'])).all()
    elif request.form['ownertel']:
        contact_list = Contact.query.filter(and_(Contact.user_id == g.user.id,Contact.ownertel ==request.form['ownertel'])).all()
    else:
        contact_list = ""
    return render_template('contact/result.html', contact_list=contact_list, ownernum4=request.form['ownernum4'],ownername =request.form['ownername'],
                           ownertel=request.form['ownertel'])

mycar/views/dpfcar_views.py
from flask import Blueprint, render_template, url_for, request, flash
from werkzeug.utils import redirect
from werkzeug.utils import secure_filename
import mycar.searchnum
from mycar.models import Dpfcar
from sqlalchemy import or_, and_
from mycar.views.auth_views import login_required
import pandas as pd


bp = Blueprint('dpfcar', __name__, url_prefix='/dpfcar')

@bp.route('/result', methods=('POST',))
@login_required
def result():
    if request.form['carnumber']:
        carnumber = request.form['carnumber']
        carnumin = carnumber[-4:]
        car_num4_01 = carnumber[:-4]+carnumin[0:2] + "**"
        car_num4_02 = carnumber[:-4]+carnumin[0] + "**" + carnumin[3]
        car_num4_03 = carnumber[:-4]+"**" + carnumin[2:4]
        carkind = request.form['carkind']
        if request.form['carkind']:
            dpfcar_list = Dpfcar.query.filter(and_(
                or_(Dpfcar.carnumber == car_num4_01,
                    Dpfcar.carnumber == car_num4_02,
                    Dpfcar.carnumber == car_num4_03),
                Dpfcar.carkind == carkind)).all()
        else:
            dpfcar_list = Dpfcar.query.filter(
                or_(Dpfcar.carnumber == car_num4_01,
                    Dpfcar.carnumber == car_num4_02,
                    Dpfcar.carnumber == car_num4_03)).all()
    else:
        dpfcar_list = ""
    return render_template('search/result.html', dpfcar_list=dpfcar_list,carnumber=carnumber ,carkind=carkind)

@bp.route('/img_result', methods=('GET','POST'))
@login_required
def img_result():
    if request.method == 'POST':
        carnumimg= request.files['file'].read()

        # print(secure_filename(f.filename))
        try:
            carnumber = mycar.searchnum.search_num(carnumimg)
        except:
            flash('차량번호 이미지 찾기가 실패하였습니다.')
            # carnumber = ""
            # dpfcar_list = ""
            # return render_template('search/result.html', dpfcar_list=dpfcar_list, carnumber=carnumber)
            return redirect(url_for('dpfcar.go_imgbase'))
        carnumin = carnumber[-4:]
        car_num4_01 = carnumber[:-4]+carnumin[0:2] + "**"
        car_num4_02 = carnumber[:-4]+carnumin[0] + "**" + carnumin[3]
        car_num4_03 = carnumber[:-4]+"**" + carnumin[2:4]

        dpfcar_list = Dpfcar.query.filter(
            or_(Dpfcar.carnumber == car_num4_01,
                Dpfcar.carnumber == car_num4_02,
                Dpfcar.carnumber == car_num4_03)).all()
    else:
        dpfcar_list = ""
    return render_template('search/result.html', dpfcar_list=dpfcar_list,carnumber=carnumber )

@bp.route('/go_base', methods=('GET','POST'))
@login_required
def go_base():
    return render_template('search/base.html')

@bp.route('/go_imgbase', methods=('GET','POST'))
@login_required
def go_imgbase():
    return render_template('search/imgbase.html')

mycar/templates/contact/regit.html
{% extends 'basic.html' %}
{% block content %}

 <div class="tm-call-to-action-box">

            <div class="tm-call-to-action-text">
            <h3 class="tm-call-to-action-title">
                고객 접촉내역 등록 및 관리
            </h3>
            <form action="{{ url_for('contact.create') }}" method="post" class="tm-call-to-action-form" >
                <input type="hidden" name="carid" value="{{ dpfcar_one.id }}" >
                <label>DPF번호:</label>
                <input type="text" name="carnumber" id="carnumber" class="tm-car-input" style="width:150px" value="{{ dpfcar_one.carnumber }}" disabled=""><br>
                <label>차량연식:</label>
                <input type="text" name="caryear" class="tm-car-input" style="width:100px" value="{{ dpfcar_one.caryear }}" disabled=""><br>
                <label>차량차종:</label>
                <input type="text" name="carkind" class="tm-car-input" style="width:100px" value="{{ dpfcar_one.carkind }}" disabled=""><br>
                <label>차량뒷번:</label>
                <input type="number" name="ownernum4" id="ownernum4" class="tm-car-input" style="width:100px" min="0000" max="9999" required="" value=""><br>
                <label>소유자명:</label>
                <input type="text" name="ownername" class="tm-car-input" style="width:150px" maxlength="30" required="" value="" ><br>
                <label>소유자폰:</label>
                <input type="text" name="ownertel" class="tm-car-input" style="width:200px" maxlength="30" required="" value=""><br>
                <label>기타사항:</label>
                <textarea name="owneretc" class="tm-car-input" style="width:500px" rows="5"></textarea><br>

                <br>

                <button carnumber class="btn btn-primary" onclick="return createchk();">
                <strong>등록</strong>
                </button>
            </form>
            </div>
 </div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
function createchk(){
    var num4 = document.getElementById("ownernum4").value;
    var num41 = "**"+num4.substr(2,2);
    var num42 = num4.substr(0,1)+"**"+ num4.substr(3,1);
    var num43 = num4.substr(0,2)+"**";

    var car4 = document.getElementById("carnumber").value.substr(-4);

    if (car4==num41 || car4==num42 || car4==num43){
        return confirm('변경한 내용을 저장하시겠습니까?');
    }else{
        alert("차량뒷 4자리 숫자를 확인해 주세요. DPF번호와 부합하지 않습니다.");
        return false;
    }
}
</script>
{% endblock %}

mycar/templates/contact/result.html
{% extends 'basic.html' %}
{% block content %}

        <div class="tm-call-to-action-box">

            <div class="tm-call-to-action-text">
                <li>
                <a class="nav-link" href="{{ url_for('dpfcar.go_base') }}">번호 검색으로</a>&nbsp;&nbsp;
                <a class="nav-link" href="{{ url_for('dpfcar.go_imgbase') }}">이미지 검색으로</a>&nbsp;
                </li>
            <h3 class="tm-call-to-action-title">
                나의 고객 관리
            </h3>
                <p class="tm-call-to-action-description">
            나의 고객중에서 차량번호의 뒷 숫자4자리 또는 차량소유자의 이름이나 전화번호로 조회가 가능합니다.
        </p>
            <form action="{{ url_for('contact.resultby') }}" class="tm-call-to-action-form" method="post">
                <label for="">검색요건</label>
                <input type="number" name="ownernum4" id="ownernum4" placeholder="차량뒷 4숫자" min="0000" max="9999" class="tm-car-input" value = "{{ ownernum4 }}">
                <input type="text" name="ownername" id="ownername" placeholder="소유자명" class="tm-car-input" value = "{{ ownername }}">
                <input type="text" name="ownertel" id="ownertel" placeholder="전화번호" class="tm-car-input" value = "{{ ownertel }}">

                <button type="submit" class="btn btn-primary" onclick="return searchchk();">
                <strong>검색</strong>
                </button>
            </form>
            </div>
        </div>
        <div>

            <table style="width:100%">
                <thead>
                <tr class="table-head-tr">
                    <td>DPF 번호</td>
                    <td>차량 연식</td>
                    <td>차량뒷 4숫자</td>
                    <td>소유자 명</td>
                    <td>전화 번호</td>
                    <td>기타 사항</td>
                    <td>등록일</td>
                    <td>구 분</td>

                </tr>
                </thead>
                <tbody>
                {% if contact_list %}
                    {% for contact in contact_list %}

                        <tr>
                            <td>{{ contact.dpfcar.carnumber }}</td>
                            <td>{{ contact.dpfcar.caryear }}</td>
                            <td>{{ contact.ownernum4 }}</td>
                            <td>{{ contact.ownername }}</td>
                            <td>{{ contact.ownertel }}</td>
                            <td>{{ contact.owneretc }}</td>
                            <td>{{ contact.create_date|datetime }}</td>

                            <td><a href="{{ url_for('contact.modify', contact_id=contact.id) }}" >변경</a>
                            <a href="{{ url_for('contact.delete', contact_id=contact.id) }}" onclick="return delchk();">삭제</a></td>

                        </tr>
                    {% endfor %}

                {% else %}
                    <tr>
                        <td colspan = "8" >** 검색 결과가 없습니다.**</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
function delchk(){
    return confirm("삭제하시겠습니까?");
}

function searchchk(){
    if (document.getElementById("carnumber4").value || document.getElementById("ownername").value || document.getElementById("ownertel").value){
        return ;
    }else{
        alert("검색 내용이 없습니다. 검색할 사항을 입력해 주세요");
        return false;
    }
}
</script>
{% endblock %}

mycar/templates/contact/update.html
{% extends 'basic.html' %}
{% block content %}
      <div class="tm-call-to-action-box">

            <div class="tm-call-to-action-text">
            <h3 class="tm-call-to-action-title">
                나의 고객 관리
            </h3>
            <form action="{{ url_for('contact.update') }}" method="post" class="tm-call-to-action-form">
                <input type="hidden" name="contactid" value="{{ contact_one.id }}" >
                <label>DPF번호:</label>
                <input type="text" name="carnumber" id="carnumber" class="tm-car-input" style="width:150px" value="{{ contact_one.dpfcar.carnumber }}" disabled=""><br>
                <label>차량연식:</label>
                <input type="text" name="caryear" class="tm-car-input" style="width:100px" value="{{ contact_one.dpfcar.caryear }}" disabled=""><br>
                <label>차량차종:</label>
                <input type="text" name="carkind" class="tm-car-input" style="width:100px" value="{{ contact_one.dpfcar.carkind }}" disabled=""><br>
                <label>차량뒷번:</label>
                <input type="number" name="ownernum4" id ="ownernum4" class="tm-car-input" style="width:100px" min="0000" max="9999" required="" value="{{ contact_one.ownernum4 }}"><br>
                <label>소유자명:</label>
                <input type="text" name="ownername" class="tm-car-input" style="width:150px" maxlength="30" required="" value="{{ contact_one.ownername }}" ><br>
                <label>소유자폰:</label>
                <input type="text" name="ownertel" class="tm-car-input" style="width:200px" maxlength="30" required="" value="{{ contact_one.ownertel }}"><br>
                <label>기타사항:</label>
                <textarea name="owneretc" class="tm-car-input" style="width:500px" rows="5" >{{ contact_one.owneretc }}</textarea><br>

                <br>

                <button type="submit" class="btn btn-primary" onclick="return createchk();">
                <strong>변경</strong>
                </button>
            </form>
            </div>

      </div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
function createchk(){
    var num4 = document.getElementById("ownernum4").value;
    var num41 = "**"+num4.substr(2,2);
    var num42 = num4.substr(0,1)+"**"+ num4.substr(3,1);
    var num43 = num4.substr(0,2)+"**";

    var car4 = document.getElementById("carnumber").value.substr(-4);

    if (car4==num41 || car4==num42 || car4==num43){
        return confirm('변경한 내용을 저장하시겠습니까?');
    }else{
        alert("차량뒷 4자리 숫자를 확인해 주세요. DPF번호와 부합하지 않습니다.");
        return false;
    }
}
</script>
{% endblock %}